import Head from 'next/head'
import Feed from '../Components/Feed';
import Sidebar from '../Components/Sidebar';
import Widgets from '../Components/Widgets';



export default function Home({newsResults,randomUserResults}) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen max-w-7xl mx-auto'>
      {/* Sidebar */}
        <Sidebar />

      {/* Feed */}
        <Feed />

      {/* Widjets */}
        <Widgets newsResults={newsResults?.articles}
          randomUserResults={randomUserResults?.results} />

      {/* Modal */}


      </main>
    </div>
  )
}


//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json


export async function getServerSideProps() {
  const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/health/in.json").then((res) => res.json());

  // Who to follow section

  const randomUserResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then((res) => res.json());
  return {
    props: {
      newsResults,
      randomUserResults,
    }
  }
}
